"""
Syllabus Filter service.

Implements PRD §4.3 — the flagship two-stage LLM pipeline that accepts
a syllabus and notes, extracts topics from the syllabus (Stage 1), then
filters the notes to retain only syllabus-relevant content (Stage 2).

Output follows the format specified in PRD §6.3.
"""

import time

import structlog

from app.services.llm_client import send_prompt
from app.utils.exceptions import FilterInputError

logger = structlog.get_logger(__name__)

# ---------------------------------------------------------------------------
# Prompt templates (PRD §6.2)
# ---------------------------------------------------------------------------

STAGE_1_SYSTEM_PROMPT = """You are an elite academic syllabus parser.
Extract all topics and sub-topics from the provided syllabus into a formal, hierarchical Harvard Outline format.

Outline Structure:
I. Major Topic Heading
   A. Primary Sub-topic
      1. Specific Detail or Concept

- Maintain the professional terminology used in the syllabus.
- Ensure the outline is exhaustive and logically organized for exam preparation.
- Format strictly as a Markdown document."""

STAGE_1_USER_PROMPT_TEMPLATE = """{syllabus_text}"""

STAGE_2_SYSTEM_PROMPT = """You are an elite academic filter and relevancy mapper.
Your goal is to produce a polished, high-level study guide that maps raw student notes to the formal course requirements.

Operational Rules:
1. Academic Rigor: Cross-reference the notes against the Harvard Outline topics provided below.
2. Content Inclusivity: Only omit notes that are clearly unrelated (>80% irrelevant). Preserve all academic data.
3. Harvard Structure:
   ## [Roman Numeral]. [Topic Name]
   [Professional, well-organized notes from the source that correspond to this syllabus topic]
4. Multi-Mapping: If a section of the notes relates to multiple topics, include it under all relevant headings.
5. Verbatim Fidelity: Retain the original technical wording and definitions from the notes.
6. Clean Synthesis: Remove logistical metadata, dates, or non-academic headers.

=== HARVARD SYLLABUS OUTLINE ===
{topics}"""

STAGE_2_USER_PROMPT_TEMPLATE = """{notes_text}"""


# ---------------------------------------------------------------------------
# Pipeline functions
# ---------------------------------------------------------------------------

def parse_syllabus(syllabus_text: str, model: str | None = None) -> str:
    """
    Stage 1 — Extract structured topics from syllabus text.
    """
    logger.info("syllabus_parse_started", text_length=len(syllabus_text))

    user_prompt = STAGE_1_USER_PROMPT_TEMPLATE.format(syllabus_text=syllabus_text)

    topics = send_prompt(
        user_prompt=user_prompt,
        system_prompt=STAGE_1_SYSTEM_PROMPT,
        model=model,
        temperature=0.0,
    )

    logger.info("syllabus_parse_completed", topics_length=len(topics))
    return topics


def filter_notes(notes_text: str, topics: str, model: str | None = None) -> str:
    """
    Stage 2 — Filter notes for syllabus relevance.
    """
    logger.info("notes_filter_started", text_length=len(notes_text))

    system_prompt = STAGE_2_SYSTEM_PROMPT.format(topics=topics)
    user_prompt = STAGE_2_USER_PROMPT_TEMPLATE.format(notes_text=notes_text)

    filtered = send_prompt(
        user_prompt=user_prompt,
        system_prompt=system_prompt,
        model=model,
        temperature=0.0,
    )

    logger.info("notes_filter_completed", filtered_length=len(filtered))
    return filtered


def format_output(topics: str, filtered_notes: str) -> str:
    """
    Format the final output as a professional academic Markdown document.
    """
    return (
        f"# Course Synthesis & Relevancy Report\n\n"
        f"Generated by CodeLens Academic Analysis Engine.\n\n"
        f"This report provides a formal mapping of the course syllabus topics against student-provided notes, "
        f"structured for comprehensive academic review and examination preparation.\n\n"
        f"## I. Course Curriculum Framework\n"
        f"{topics}\n\n"
        f"---\n\n"
        f"## II. Detailed Academic Synthesis\n"
        f"{filtered_notes}"
    )


def run_filter(
    syllabus_text: str,
    notes_text: str,
    model: str | None = None,
) -> dict:
    """
    Execute the complete two-stage Syllabus Filter pipeline.

    Orchestrates Stage 1 (syllabus parsing) and Stage 2 (notes filtering),
    validates inputs upfront (PRD §6.4), tracks processing time, and
    returns the formatted output.

    Args:
        syllabus_text: Plain text of the syllabus.
        notes_text: Plain text of the notes.
        model: Optional LLM model override.

    Returns:
        Dictionary with keys:
        - 'identified_topics': Stage 1 output
        - 'filtered_notes': Stage 2 output
        - 'formatted_output': Combined output per PRD §6.3
        - 'processing_time_seconds': Total processing time
        - 'model_used': The model used

    Raises:
        FilterInputError: If either input is missing or empty (PRD §6.4).
    """
    # Validate inputs upfront before any API call (PRD §6.4)
    if not syllabus_text or not syllabus_text.strip():
        raise FilterInputError("Syllabus text is required and cannot be empty.")
    if not notes_text or not notes_text.strip():
        raise FilterInputError("Notes text is required and cannot be empty.")

    from app.config import get_settings
    model = model or get_settings().DEFAULT_MODEL

    logger.info(
        "filter_pipeline_started",
        syllabus_length=len(syllabus_text),
        notes_length=len(notes_text),
        model=model,
    )

    start_time = time.time()

    # Stage 1: Parse syllabus topics
    topics = parse_syllabus(syllabus_text, model=model)

    # Stage 2: Filter notes against topics
    filtered = filter_notes(notes_text, topics, model=model)

    processing_time = round(time.time() - start_time, 2)

    # Format output per PRD §6.3
    formatted = format_output(topics, filtered)

    logger.info(
        "filter_pipeline_completed",
        processing_time=processing_time,
        topics_length=len(topics),
        filtered_length=len(filtered),
    )

    return {
        "identified_topics": topics,
        "filtered_notes": filtered,
        "formatted_output": formatted,
        "processing_time_seconds": processing_time,
        "model_used": model,
    }
